"""empty message

Revision ID: 1644017a7118
Revises: 
Create Date: 2024-03-17 19:45:25.090148

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1644017a7118'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
